### PR TITLE
Adding GCM support

### PR DESCRIPTION
**Pull request by vash15**
I have added a new protocol for gcm, updated documentation and write some test. If you can pull it.

### CODE REVIEW

**Comment by gregberge** [comment]
Thanks, i will review it and merge it around the 8/25 (holidays).

**Comment by vash15** [comment]
Thank you and happy holidays.

**Comment by gregberge** [comment]
I have just updated the project in version 0.3.0 with GCM support. I have refactored sending and events. Thanks.

**Comment by vash15** [comment]
Best,neoziro.

**Pull request merged**
