### PR TITLE
add WNS support

### PR DESCRIPTION
**Pull request by yanhick**
Microsoft has a new push notification protocol for windows 8.1.
This implements sending notifications to the MS servers. 

I've tested the code using actual device and app id and I get 200 from MS servers.
I couldn't test on a device for now

### CODE REVIEW

**Comment by gregberge** [comment]
Released https://github.com/neoziro/push-notify/releases/tag/v1.1.0

**Comment by yanhick** [comment]
wow, merci c’était rapide !

**Comment by gregberge** [comment]
:rocket:

**Comment by yanhick** [comment]
Tu ferais pas une release npm dans la foulé par hasard ?

**Comment by gregberge** [comment]
@yanhick c'est bon

**Comment by yanhick** [comment]
Quel artiste !

2014-07-29 16:49 GMT+02:00 Greg Bergé notifications@github.com:

**Pull request merged**
